//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Visual Notes.rc
//
#define IDS_FLOWCHARTSET                1
#define ID_BUTTON_MORE                  3
#define IDC_BUTTON_EXTDDLG              4
#define IDC_ADDNEW                      4
#define IDD_ABOUTBOX                    100
#define IDD_ABOUTBOX1                   101
#define IDS_EDIT                        102
#define IDS_TOOL                        103
#define IDM_MENU                        104
#define IDR_MAIN_EDIT                   105
#define IDR_MAIN_TOOL                   106
#define IDR_DOC_TOOL                    107
#define IDM_DOCLIST                     108
#define IDR_MAINFRAME                   128
#define IDI_ICON1                       131
#define IDR_TOOLBAR_FLOWCHART           132
#define IDB_LOGO                        133
#define IDR_TOOLBAR_GENERAL             137
#define IDD_SYMBOLPROPERTY              140
#define IDD_COLORPICKER                 141
#define IDD_SYMBOLTEXT                  142
#define IDR_TOOLBAR_GENERAL2            144
#define IDR_TOOLBAR_SHOWHIDETOOLS       146
#define IDR_TOOLBAR_EDGESET1            148
#define IDR_TOOLBAR_UML                 150
#define IDR_TOOLBAR_NET1                152
#define IDR_TOOLBAR_NET2                154
#define IDB_CLIENT1                     160
#define IDB_CLIENT2                     162
#define IDB_SERVER1                     164
#define IDB_BEEPER1                     165
#define IDB_CAMERA1                     166
#define IDB_CAMERA2                     167
#define IDB_CLIENT3                     168
#define IDB_CLIENT4                     170
#define IDB_POCKETPC1                   171
#define IDB_DATABASE                    174
#define IDB_BEEPER2                     175
#define IDB_FAX1                        176
#define IDB_FAX3                        178
#define IDB_HUB1                        179
#define IDB_HUB2                        180
#define IDB_CLIENTMAC                   181
#define IDB_PRINTER1                    183
#define IDB_THINKPAD3                   184
#define IDB_PALM1                       185
#define IDB_PALM2                       186
#define IDB_PALM3                       187
#define IDB_CELLPHONE                   188
#define IDB_PRINTER3                    189
#define IDB_PRINTER4                    190
#define IDB_PRINTER5                    191
#define IDB_PRINTER2                    192
#define IDB_POCKETPC2                   193
#define IDB_SERVER2                     195
#define IDB_THINKPAD1                   198
#define IDB_THINKPAD2                   199
#define IDB_MODEM                       201
#define IDB_IBMMAINFRAME                203
#define IDD_BMSYMBOLPROPERTY            204
#define IDD_REGISTRATIONDLG             205
#define IDD_APPSETTINGS                 213
#define IDD_EDGEPROPERTY                217
#define IDD_DOCSETTINGS                 218
#define IDD_DIAGRAMVIEW                 220
#define IDD_NEWNOTE                     221
#define IDD_SYMBOLPROPERTY2             222
#define IDD_UMLCLASSPROPERTY            223
#define IDD_UMLCOMPONENTPROPERTY        224
#define IDR_TOOLBAR_ALIGNMENT           225
#define IDR_TOOLBAR_SHOWHIDE            229
#define IDB_DISH1                       240
#define IDB_SATELLITE                   241
#define IDC_EDIT1                       1000
#define IDC_EDIT_CANVASY                1001
#define IDC_EDIT_GREEN                  1001
#define IDC_EDIT_CURRENTDIAGRAM         1001
#define IDC_EDIT_AUTHCODE               1001
#define IDC_EDIT_BLUE                   1002
#define IDC_EDIT_SELECTEDDIAGRAM        1002
#define IDC_EDIT_USERNAME               1002
#define IDC_CHECK_DIRECTEDGEAA          1003
#define IDC_EDIT_SYMBOLHEIGHT           1011
#define IDC_EDIT_SYMBOLWIDTH            1012
#define IDC_BUTTON_CLRPICK              1041
#define IDC_EDIT_RED                    1042
#define IDC_EDIT_SYMBOLTEXT             1045
#define IDC_COMBO_FONTSTYLE             1046
#define IDC_COMBO_FONTSIZE              1047
#define IDC_BUTTON_FONTCOLOR            1052
#define IDC_CLRBUTTON01                 1054
#define IDC_CLRBUTTON02                 1055
#define IDC_CLRBUTTON03                 1056
#define IDC_CLRBUTTON04                 1057
#define IDC_CLRBUTTON05                 1058
#define IDC_BMPBUTTON_CURRENT           1059
#define IDC_CLRBUTTON06                 1059
#define IDC_LIST_AVAILABLEBMPS          1060
#define IDC_CLRBUTTON07                 1060
#define IDC_CHECK_ALLOWSTRECHING        1061
#define IDC_CLRBUTTON08                 1061
#define IDC_BMPBUTTON_PREVIEW           1062
#define IDC_CLRBUTTON09                 1062
#define IDC_CLRBUTTON10                 1063
#define IDC_CLRBUTTON11                 1064
#define IDC_CLRBUTTON12                 1065
#define IDC_BUTTON_REGISTER             1065
#define IDC_CLRBUTTON13                 1066
#define IDC_EDIT_KEY                    1066
#define IDC_CLRBUTTON14                 1067
#define IDC_EDIT_NAME                   1067
#define IDC_CLRBUTTON15                 1068
#define IDC_CLRBUTTON16                 1069
#define IDC_STATIC_LOGO                 1069
#define IDC_CLRBUTTON17                 1070
#define IDC_CHECK_CENTERED              1070
#define IDC_CLRBUTTON18                 1071
#define IDC_CLRBUTTON19                 1072
#define IDC_CHECK_BOLD                  1072
#define IDC_CLRBUTTON20                 1073
#define IDC_CLRBUTTON21                 1074
#define IDC_CLRBUTTON22                 1075
#define IDC_COMBO_MASTERSYMBOL          1075
#define IDC_CHECK_UNLINKONCD            1076
#define IDC_CLRBUTTON23                 1076
#define IDC_CHECK_ITALIC                1076
#define IDC_CLRBUTTON24                 1077
#define IDC_BUTTON_JOINTCOLOR           1077
#define IDC_CLRBUTTON25                 1078
#define IDC_BUTTON_EDGECOLOR            1078
#define IDC_BUTTON_ADDNEW               1078
#define IDC_CLRBUTTON26                 1079
#define IDC_CLRBUTTON27                 1080
#define IDC_CLRBUTTON_SECONDARY         1080
#define IDC_CLRBUTTON28                 1081
#define IDC_CLRBUTTON29                 1082
#define IDC_CLRBUTTON30                 1083
#define IDC_CLRBUTTON31                 1084
#define IDC_COMBO_SLAVESYMBOL           1084
#define IDC_CLRBUTTON32                 1085
#define IDC_COMBO_EDGEWIDTH             1085
#define IDC_CLRBUTTON33                 1086
#define IDC_CLRBUTTON34                 1087
#define IDC_CLRBUTTON35                 1088
#define IDC_CLRBUTTON36                 1089
#define IDC_CLRBUTTON37                 1090
#define IDC_CLRBUTTON38                 1091
#define IDC_CLRBUTTON39                 1092
#define IDC_CLRBUTTON40                 1093
#define IDC_CLRBUTTON41                 1094
#define IDC_CLRBUTTON42                 1095
#define IDC_RADIO_SOLID                 1095
#define IDC_CLRBUTTON43                 1096
#define IDC_CLRBUTTON44                 1097
#define IDC_RADIO_DASH                  1097
#define IDC_CLRBUTTON45                 1098
#define IDC_CLRBUTTON46                 1099
#define IDC_CHECK_REMOVECHILDREN        1100
#define IDC_CLRBUTTON47                 1100
#define IDC_CLRBUTTON48                 1101
#define IDC_CHECK_LOCKDIAGRAM           1101
#define IDC_EDIT_CANVASX                1102
#define IDC_CLRBUTTON49                 1102
#define IDC_COMBO_TREEDIR               1103
#define IDC_BUTTON_LOADDEFAULT          1104
#define IDC_BUTTON_RESTOREDEFAULT       1104
#define IDC_CHECK_SAVESETTINGS          1106
#define IDC_CHECK_AUTOREMOVELINK        1107
#define IDC_LIST1                       1108
#define IDC_BUTTON_VISIT                1111
#define IDC_BUTTON_DELETE               1112
#define IDC_BUTTON_DELETEALL            1113
#define IDC_LIST_DIAGRAMS               1114
#define IDC_BUTTON_RENAME               1115
#define IDC_LIST_FILES                  1122
#define IDC_COMBO_LOOKIN                1123
#define IDC_CLRBUTTON_EDGE              1124
#define IDC_CLRBUTTON_CAPTION           1125
#define IDC_CLRBUTTON_BKGND             1126
#define IDC_RADIO_SOLIDEDGE             1127
#define IDC_RADIO_DASHEDEDGE            1128
#define IDC_CHECK_MAKECURRENT           1129
#define IDC_EDIT_EMBEDDEDLINK           1130
#define IDC_EDIT_NOTELINK               1131
#define IDC_STATIC_SYMBOLCOLORS         1132
#define IDC_STATIC_LABELPROPERTIES      1133
#define IDC_STATIC_JOINTCOLORGROUPBOX   1134
#define IDC_EDIT_SELMETHOD              1135
#define IDC_EDIT_CLASSTITLE             1136
#define IDC_LIST_METHODS                1137
#define IDC_EDIT_SELINTERFACE           1138
#define IDC_LIST_INTERFACES             1139
#define IDC_EDIT_CAPTION                1140
#define IDC_CHECK_UNDERLINE             1141
#define ID_TOOLS_SETTINGS               32771
#define ID_TOOLS_DIAGRAM                32772
#define ID_TOOLS_EXPORT                 32774
#define ID_TOOLBTN_CIRCLE               32777
#define ID_TOOLBTN_DIAMOND              32779
#define ID_TOOLBTN_RECTANGLE            32780
#define ID_TOOLBTN_SHEAR                32790
#define ID_TOOLBTN_TRACK                32804
#define ID_TOOLBTN_SELECT               32818
#define IDS_EDGESET1                    32850
#define IDS_UMLCLASS_EMPTYTITLEBAR      32851
#define IDS_UMLCLASS_EMPTYMETHODLIST    32852
#define ID_TOOLBTN_CREATE               32853
#define IDS_UMLSET                      32853
#define ID_TOOLBTN_PROPERTIES           32854
#define IDS_NET1SET                     32854
#define IDS_NET2SET                     32855
#define IDS_LOGICSET                    32856
#define IDS_TREEDIR_UP                  32857
#define IDS_TREEDIR_DOWN                32858
#define ID_TOOLBTN_DELETE               32859
#define IDS_TREEDIR_LEFT                32859
#define ID_TOOLBTN_UNDO                 32860
#define IDS_TREEDIR_RIGHT               32860
#define IDS_ALIGNSET                    32861
#define IDS_SHOWHIDESET                 32862
#define IDS_APPSIG                      32863
#define ID_TOOLBTN_REDO                 32864
#define ID_TOOLBTN_HELP                 32865
#define ID_TOOLBTN_LINK                 32866
#define ID_TOOLBTN_SHOWHIDETOOLS        32870
#define ID_TOOLBTN_EDGE                 32879
#define ID_TOOLBTN_CMPLXEDGE            32884
#define ID_TOOLBTN_BASICEDGE            32885
#define ID_TOOLBTN_UMLACTOR             32886
#define ID_TOOLBTN_UMLNOTE              32888
#define ID_TOOLBTN_UMLPACKAGE           32889
#define ID_TOOLBTN_UMLCOMPONENT         32890
#define ID_TOOLBTN_UMLCLASS             32891
#define ID_TOOLBTN_UMLCASE              32892
#define ID_TOOLBTN_NETCLIENT            32895
#define ID_TOOLBTN_NETSERVER            32896
#define ID_TOOLBTN_NETDATABASE          32899
#define ID_TOOLBTN_NETCLOUD             32900
#define ID_TOOLBTN_NETPRINTER           32902
#define ID_TOOLBTN_NETHUB               32905
#define ID_TOOLBTN_NETMAINFRAME         32910
#define ID_TOOLBTN_NET2SATELLITE        32913
#define ID_TOOLBTN_NET2DISH             32914
#define ID_TOOLBTN_NET2CELLPHONE        32915
#define ID_TOOLBTN_NET2PDA              32916
#define ID_TOOLBTN_NET2THINKPAD         32917
#define ID_TOOLBTN_NET2CAMERA           32918
#define ID_TOOLBTN_NET2FAX              32919
#define ID_TOOLBTN_NET2WIREPHONE        32921
#define ID_TOOLBTN_TEXT                 32942
#define ID_TOOLBTN_DEPBASICEDGE         32943
#define ID_TOOLBTN_ALIGN_TOP            32973
#define ID_TOOBTN_ALIGN_RIGHT           32975
#define ID_TOOLBTN_ALIGN_LEFT           32976
#define ID_TOOLBTN_ALIGN_SIZE           32978
#define ID_TOOLBTN_ALIGN_BOTTOM         32983
#define ID_TOOLBTN_GENERALIZE           32984
#define ID_TOOLBTN_TAGA                 32985
#define ID_TOOLBTN_TAGB                 32986
#define ID_TOOLBTN_DEPLOYMENT           32987
#define ID_TOOLBTN_ROUNDRECT            32989
#define ID_TOOLBTN_CAPSULE              32991
#define ID_TOOLBTN_ALIGNCENTER          32992
#define ID_TOOLBTN_SHOW_HIDDEN          32999
#define ID_TOOLBTN_HIDE_SELECTED        33000
#define ID_TOOLBTN_NETRING              33001
#define IDS_NEW                         65000
#define IDS_FILE                        65001
#define IDS_MHELP                       65002
#define IDS_SAVE                        65003
#define IDS_CUT                         65004
#define IDS_COPY                        65005
#define IDS_PASTE                       65006

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1004
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
